// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: consensus_envelope.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsensusEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"` // signature is contained
	SenderAddr    []byte                 `protobuf:"bytes,2,opt,name=senderAddr,proto3" json:"senderAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusEnvelope) Reset() {
	*x = ConsensusEnvelope{}
	mi := &file_consensus_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusEnvelope) ProtoMessage() {}

func (x *ConsensusEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusEnvelope.ProtoReflect.Descriptor instead.
func (*ConsensusEnvelope) Descriptor() ([]byte, []int) {
	return file_consensus_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *ConsensusEnvelope) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *ConsensusEnvelope) GetSenderAddr() []byte {
	if x != nil {
		return x.SenderAddr
	}
	return nil
}

var File_consensus_envelope_proto protoreflect.FileDescriptor

const file_consensus_envelope_proto_rawDesc = "" +
	"\n" +
	"\x18consensus_envelope.proto\x12\amessage\x1a google/protobuf/descriptor.proto\"E\n" +
	"\x11ConsensusEnvelope\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\x12\x1e\n" +
	"\n" +
	"senderAddr\x18\x02 \x01(\fR\n" +
	"senderAddrB3Z1github.com/meterio/supernova/libs/message;messageb\x06proto3"

var (
	file_consensus_envelope_proto_rawDescOnce sync.Once
	file_consensus_envelope_proto_rawDescData []byte
)

func file_consensus_envelope_proto_rawDescGZIP() []byte {
	file_consensus_envelope_proto_rawDescOnce.Do(func() {
		file_consensus_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensus_envelope_proto_rawDesc), len(file_consensus_envelope_proto_rawDesc)))
	})
	return file_consensus_envelope_proto_rawDescData
}

var file_consensus_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_consensus_envelope_proto_goTypes = []any{
	(*ConsensusEnvelope)(nil), // 0: message.ConsensusEnvelope
}
var file_consensus_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_consensus_envelope_proto_init() }
func file_consensus_envelope_proto_init() {
	if File_consensus_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensus_envelope_proto_rawDesc), len(file_consensus_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_envelope_proto_goTypes,
		DependencyIndexes: file_consensus_envelope_proto_depIdxs,
		MessageInfos:      file_consensus_envelope_proto_msgTypes,
	}.Build()
	File_consensus_envelope_proto = out.File
	file_consensus_envelope_proto_goTypes = nil
	file_consensus_envelope_proto_depIdxs = nil
}
