// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: rpc_envelope.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       uint32                 `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Raw           []byte                 `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	IsResponse    bool                   `protobuf:"varint,3,opt,name=isResponse,proto3" json:"isResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCEnvelope) Reset() {
	*x = RPCEnvelope{}
	mi := &file_rpc_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCEnvelope) ProtoMessage() {}

func (x *RPCEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCEnvelope.ProtoReflect.Descriptor instead.
func (*RPCEnvelope) Descriptor() ([]byte, []int) {
	return file_rpc_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *RPCEnvelope) GetMsgType() uint32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *RPCEnvelope) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *RPCEnvelope) GetIsResponse() bool {
	if x != nil {
		return x.IsResponse
	}
	return false
}

var File_rpc_envelope_proto protoreflect.FileDescriptor

const file_rpc_envelope_proto_rawDesc = "" +
	"\n" +
	"\x12rpc_envelope.proto\x12\amessage\"Y\n" +
	"\vRPCEnvelope\x12\x18\n" +
	"\amsgType\x18\x01 \x01(\rR\amsgType\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\x12\x1e\n" +
	"\n" +
	"isResponse\x18\x03 \x01(\bR\n" +
	"isResponseB3Z1github.com/meterio/supernova/libs/message;messageb\x06proto3"

var (
	file_rpc_envelope_proto_rawDescOnce sync.Once
	file_rpc_envelope_proto_rawDescData []byte
)

func file_rpc_envelope_proto_rawDescGZIP() []byte {
	file_rpc_envelope_proto_rawDescOnce.Do(func() {
		file_rpc_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_envelope_proto_rawDesc), len(file_rpc_envelope_proto_rawDesc)))
	})
	return file_rpc_envelope_proto_rawDescData
}

var file_rpc_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_envelope_proto_goTypes = []any{
	(*RPCEnvelope)(nil), // 0: message.RPCEnvelope
}
var file_rpc_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_envelope_proto_init() }
func file_rpc_envelope_proto_init() {
	if File_rpc_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_envelope_proto_rawDesc), len(file_rpc_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_envelope_proto_goTypes,
		DependencyIndexes: file_rpc_envelope_proto_depIdxs,
		MessageInfos:      file_rpc_envelope_proto_msgTypes,
	}.Build()
	File_rpc_envelope_proto = out.File
	file_rpc_envelope_proto_goTypes = nil
	file_rpc_envelope_proto_depIdxs = nil
}
