// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: sync_message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCRequestEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enum          uint32                 `protobuf:"varint,1,opt,name=enum,proto3" json:"enum,omitempty"`
	Raw           []byte                 `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty" ssz-max:"1048576"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCRequestEnvelope) Reset() {
	*x = RPCRequestEnvelope{}
	mi := &file_sync_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCRequestEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCRequestEnvelope) ProtoMessage() {}

func (x *RPCRequestEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sync_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCRequestEnvelope.ProtoReflect.Descriptor instead.
func (*RPCRequestEnvelope) Descriptor() ([]byte, []int) {
	return file_sync_message_proto_rawDescGZIP(), []int{0}
}

func (x *RPCRequestEnvelope) GetEnum() uint32 {
	if x != nil {
		return x.Enum
	}
	return 0
}

func (x *RPCRequestEnvelope) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type RPCResponseEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enum          uint32                 `protobuf:"varint,1,opt,name=enum,proto3" json:"enum,omitempty"`
	Raw           []byte                 `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty" ssz-max:"1048576"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCResponseEnvelope) Reset() {
	*x = RPCResponseEnvelope{}
	mi := &file_sync_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCResponseEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCResponseEnvelope) ProtoMessage() {}

func (x *RPCResponseEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_sync_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCResponseEnvelope.ProtoReflect.Descriptor instead.
func (*RPCResponseEnvelope) Descriptor() ([]byte, []int) {
	return file_sync_message_proto_rawDescGZIP(), []int{1}
}

func (x *RPCResponseEnvelope) GetEnum() uint32 {
	if x != nil {
		return x.Enum
	}
	return 0
}

func (x *RPCResponseEnvelope) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

var File_sync_message_proto protoreflect.FileDescriptor

var file_sync_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x0a,
	0x12, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x3b, 0x0a, 0x13, 0x52, 0x50, 0x43,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x65, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x2f, 0x73, 0x75, 0x70,
	0x65, 0x72, 0x6e, 0x6f, 0x76, 0x61, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sync_message_proto_rawDescOnce sync.Once
	file_sync_message_proto_rawDescData = file_sync_message_proto_rawDesc
)

func file_sync_message_proto_rawDescGZIP() []byte {
	file_sync_message_proto_rawDescOnce.Do(func() {
		file_sync_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_message_proto_rawDescData)
	})
	return file_sync_message_proto_rawDescData
}

var file_sync_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sync_message_proto_goTypes = []any{
	(*RPCRequestEnvelope)(nil),  // 0: message.RPCRequestEnvelope
	(*RPCResponseEnvelope)(nil), // 1: message.RPCResponseEnvelope
}
var file_sync_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sync_message_proto_init() }
func file_sync_message_proto_init() {
	if File_sync_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_message_proto_goTypes,
		DependencyIndexes: file_sync_message_proto_depIdxs,
		MessageInfos:      file_sync_message_proto_msgTypes,
	}.Build()
	File_sync_message_proto = out.File
	file_sync_message_proto_rawDesc = nil
	file_sync_message_proto_goTypes = nil
	file_sync_message_proto_depIdxs = nil
}
