// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: sync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GenesisBlockId   []byte                 `protobuf:"bytes,1,opt,name=genesis_block_id,json=genesisBlockId,proto3" json:"genesis_block_id,omitempty"`
	SysNanoTimestamp uint64                 `protobuf:"varint,2,opt,name=sys_nano_timestamp,json=sysNanoTimestamp,proto3" json:"sys_nano_timestamp,omitempty"`
	BestBlockId      []byte                 `protobuf:"bytes,3,opt,name=best_block_id,json=bestBlockId,proto3" json:"best_block_id,omitempty"`
	BestBlockNum     uint64                 `protobuf:"varint,4,opt,name=best_block_num,json=bestBlockNum,proto3" json:"best_block_num,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetGenesisBlockId() []byte {
	if x != nil {
		return x.GenesisBlockId
	}
	return nil
}

func (x *GetStatusResponse) GetSysNanoTimestamp() uint64 {
	if x != nil {
		return x.SysNanoTimestamp
	}
	return 0
}

func (x *GetStatusResponse) GetBestBlockId() []byte {
	if x != nil {
		return x.BestBlockId
	}
	return nil
}

func (x *GetStatusResponse) GetBestBlockNum() uint64 {
	if x != nil {
		return x.BestBlockNum
	}
	return 0
}

// NotifyBlock
type NotifyBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockBytes    []byte                 `protobuf:"bytes,1,opt,name=block_bytes,json=blockBytes,proto3" json:"block_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBlockRequest) Reset() {
	*x = NotifyBlockRequest{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBlockRequest) ProtoMessage() {}

func (x *NotifyBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBlockRequest.ProtoReflect.Descriptor instead.
func (*NotifyBlockRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyBlockRequest) GetBlockBytes() []byte {
	if x != nil {
		return x.BlockBytes
	}
	return nil
}

type NotifyBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBlockResponse) Reset() {
	*x = NotifyBlockResponse{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBlockResponse) ProtoMessage() {}

func (x *NotifyBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBlockResponse.ProtoReflect.Descriptor instead.
func (*NotifyBlockResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

// NotifyBlockID
type NotifyBlockIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       []byte                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBlockIDRequest) Reset() {
	*x = NotifyBlockIDRequest{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBlockIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBlockIDRequest) ProtoMessage() {}

func (x *NotifyBlockIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBlockIDRequest.ProtoReflect.Descriptor instead.
func (*NotifyBlockIDRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyBlockIDRequest) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

type NotifyBlockIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBlockIDResponse) Reset() {
	*x = NotifyBlockIDResponse{}
	mi := &file_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBlockIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBlockIDResponse) ProtoMessage() {}

func (x *NotifyBlockIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBlockIDResponse.ProtoReflect.Descriptor instead.
func (*NotifyBlockIDResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{5}
}

// NotifyTx
type NotifyTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxBytes       []byte                 `protobuf:"bytes,1,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyTxRequest) Reset() {
	*x = NotifyTxRequest{}
	mi := &file_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTxRequest) ProtoMessage() {}

func (x *NotifyTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTxRequest.ProtoReflect.Descriptor instead.
func (*NotifyTxRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyTxRequest) GetTxBytes() []byte {
	if x != nil {
		return x.TxBytes
	}
	return nil
}

type NotifyTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyTxResponse) Reset() {
	*x = NotifyTxResponse{}
	mi := &file_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTxResponse) ProtoMessage() {}

func (x *NotifyTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTxResponse.ProtoReflect.Descriptor instead.
func (*NotifyTxResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{7}
}

// GetBlockByID
type GetBlockByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxBytes       []byte                 `protobuf:"bytes,1,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByIDRequest) Reset() {
	*x = GetBlockByIDRequest{}
	mi := &file_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByIDRequest) ProtoMessage() {}

func (x *GetBlockByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByIDRequest.ProtoReflect.Descriptor instead.
func (*GetBlockByIDRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{8}
}

func (x *GetBlockByIDRequest) GetTxBytes() []byte {
	if x != nil {
		return x.TxBytes
	}
	return nil
}

type GetBlockByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockBytes    []byte                 `protobuf:"bytes,1,opt,name=block_bytes,json=blockBytes,proto3" json:"block_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByIDResponse) Reset() {
	*x = GetBlockByIDResponse{}
	mi := &file_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByIDResponse) ProtoMessage() {}

func (x *GetBlockByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByIDResponse.ProtoReflect.Descriptor instead.
func (*GetBlockByIDResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{9}
}

func (x *GetBlockByIDResponse) GetBlockBytes() []byte {
	if x != nil {
		return x.BlockBytes
	}
	return nil
}

// GetBlockIDByNumber
type GetBlockIDByNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNum      uint64                 `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockIDByNumberRequest) Reset() {
	*x = GetBlockIDByNumberRequest{}
	mi := &file_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockIDByNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockIDByNumberRequest) ProtoMessage() {}

func (x *GetBlockIDByNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockIDByNumberRequest.ProtoReflect.Descriptor instead.
func (*GetBlockIDByNumberRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlockIDByNumberRequest) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

type GetBlockIDByNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       []byte                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockIDByNumberResponse) Reset() {
	*x = GetBlockIDByNumberResponse{}
	mi := &file_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockIDByNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockIDByNumberResponse) ProtoMessage() {}

func (x *GetBlockIDByNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockIDByNumberResponse.ProtoReflect.Descriptor instead.
func (*GetBlockIDByNumberResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{11}
}

func (x *GetBlockIDByNumberResponse) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

// GetBlocksFromNumber
type GetBlocksFromNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNum      uint64                 `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksFromNumberRequest) Reset() {
	*x = GetBlocksFromNumberRequest{}
	mi := &file_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksFromNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksFromNumberRequest) ProtoMessage() {}

func (x *GetBlocksFromNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksFromNumberRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksFromNumberRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlocksFromNumberRequest) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

type GetBlocksFromNumberResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockBytesList [][]byte               `protobuf:"bytes,1,rep,name=block_bytes_list,json=blockBytesList,proto3" json:"block_bytes_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBlocksFromNumberResponse) Reset() {
	*x = GetBlocksFromNumberResponse{}
	mi := &file_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksFromNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksFromNumberResponse) ProtoMessage() {}

func (x *GetBlocksFromNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksFromNumberResponse.ProtoReflect.Descriptor instead.
func (*GetBlocksFromNumberResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{13}
}

func (x *GetBlocksFromNumberResponse) GetBlockBytesList() [][]byte {
	if x != nil {
		return x.BlockBytesList
	}
	return nil
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\x02pb\"\x12\n" +
	"\x10GetStatusRequest\"\xb5\x01\n" +
	"\x11GetStatusResponse\x12(\n" +
	"\x10genesis_block_id\x18\x01 \x01(\fR\x0egenesisBlockId\x12,\n" +
	"\x12sys_nano_timestamp\x18\x02 \x01(\x04R\x10sysNanoTimestamp\x12\"\n" +
	"\rbest_block_id\x18\x03 \x01(\fR\vbestBlockId\x12$\n" +
	"\x0ebest_block_num\x18\x04 \x01(\x04R\fbestBlockNum\"5\n" +
	"\x12NotifyBlockRequest\x12\x1f\n" +
	"\vblock_bytes\x18\x01 \x01(\fR\n" +
	"blockBytes\"\x15\n" +
	"\x13NotifyBlockResponse\"1\n" +
	"\x14NotifyBlockIDRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\fR\ablockId\"\x17\n" +
	"\x15NotifyBlockIDResponse\",\n" +
	"\x0fNotifyTxRequest\x12\x19\n" +
	"\btx_bytes\x18\x01 \x01(\fR\atxBytes\"\x12\n" +
	"\x10NotifyTxResponse\"0\n" +
	"\x13GetBlockByIDRequest\x12\x19\n" +
	"\btx_bytes\x18\x01 \x01(\fR\atxBytes\"7\n" +
	"\x14GetBlockByIDResponse\x12\x1f\n" +
	"\vblock_bytes\x18\x01 \x01(\fR\n" +
	"blockBytes\"8\n" +
	"\x19GetBlockIDByNumberRequest\x12\x1b\n" +
	"\tblock_num\x18\x01 \x01(\x04R\bblockNum\"7\n" +
	"\x1aGetBlockIDByNumberResponse\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\fR\ablockId\"9\n" +
	"\x1aGetBlocksFromNumberRequest\x12\x1b\n" +
	"\tblock_num\x18\x01 \x01(\x04R\bblockNum\"G\n" +
	"\x1bGetBlocksFromNumberResponse\x12(\n" +
	"\x10block_bytes_list\x18\x01 \x03(\fR\x0eblockBytesList2\xed\x03\n" +
	"\x04Sync\x128\n" +
	"\tGetStatus\x12\x14.pb.GetStatusRequest\x1a\x15.pb.GetStatusResponse\x12>\n" +
	"\vNotifyBlock\x12\x16.pb.NotifyBlockRequest\x1a\x17.pb.NotifyBlockResponse\x12D\n" +
	"\rNotifyBlockID\x12\x18.pb.NotifyBlockIDRequest\x1a\x19.pb.NotifyBlockIDResponse\x125\n" +
	"\bNotifyTx\x12\x13.pb.NotifyTxRequest\x1a\x14.pb.NotifyTxResponse\x12A\n" +
	"\fGetBlockByID\x12\x17.pb.GetBlockByIDRequest\x1a\x18.pb.GetBlockByIDResponse\x12S\n" +
	"\x12GetBlockIDByNumber\x12\x1d.pb.GetBlockIDByNumberRequest\x1a\x1e.pb.GetBlockIDByNumberResponse\x12V\n" +
	"\x13GetBlocksFromNumber\x12\x1e.pb.GetBlocksFromNumberRequest\x1a\x1f.pb.GetBlocksFromNumberResponseB\x0eZ\fsupernova/pbb\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sync_proto_goTypes = []any{
	(*GetStatusRequest)(nil),            // 0: pb.GetStatusRequest
	(*GetStatusResponse)(nil),           // 1: pb.GetStatusResponse
	(*NotifyBlockRequest)(nil),          // 2: pb.NotifyBlockRequest
	(*NotifyBlockResponse)(nil),         // 3: pb.NotifyBlockResponse
	(*NotifyBlockIDRequest)(nil),        // 4: pb.NotifyBlockIDRequest
	(*NotifyBlockIDResponse)(nil),       // 5: pb.NotifyBlockIDResponse
	(*NotifyTxRequest)(nil),             // 6: pb.NotifyTxRequest
	(*NotifyTxResponse)(nil),            // 7: pb.NotifyTxResponse
	(*GetBlockByIDRequest)(nil),         // 8: pb.GetBlockByIDRequest
	(*GetBlockByIDResponse)(nil),        // 9: pb.GetBlockByIDResponse
	(*GetBlockIDByNumberRequest)(nil),   // 10: pb.GetBlockIDByNumberRequest
	(*GetBlockIDByNumberResponse)(nil),  // 11: pb.GetBlockIDByNumberResponse
	(*GetBlocksFromNumberRequest)(nil),  // 12: pb.GetBlocksFromNumberRequest
	(*GetBlocksFromNumberResponse)(nil), // 13: pb.GetBlocksFromNumberResponse
}
var file_sync_proto_depIdxs = []int32{
	0,  // 0: pb.Sync.GetStatus:input_type -> pb.GetStatusRequest
	2,  // 1: pb.Sync.NotifyBlock:input_type -> pb.NotifyBlockRequest
	4,  // 2: pb.Sync.NotifyBlockID:input_type -> pb.NotifyBlockIDRequest
	6,  // 3: pb.Sync.NotifyTx:input_type -> pb.NotifyTxRequest
	8,  // 4: pb.Sync.GetBlockByID:input_type -> pb.GetBlockByIDRequest
	10, // 5: pb.Sync.GetBlockIDByNumber:input_type -> pb.GetBlockIDByNumberRequest
	12, // 6: pb.Sync.GetBlocksFromNumber:input_type -> pb.GetBlocksFromNumberRequest
	1,  // 7: pb.Sync.GetStatus:output_type -> pb.GetStatusResponse
	3,  // 8: pb.Sync.NotifyBlock:output_type -> pb.NotifyBlockResponse
	5,  // 9: pb.Sync.NotifyBlockID:output_type -> pb.NotifyBlockIDResponse
	7,  // 10: pb.Sync.NotifyTx:output_type -> pb.NotifyTxResponse
	9,  // 11: pb.Sync.GetBlockByID:output_type -> pb.GetBlockByIDResponse
	11, // 12: pb.Sync.GetBlockIDByNumber:output_type -> pb.GetBlockIDByNumberResponse
	13, // 13: pb.Sync.GetBlocksFromNumber:output_type -> pb.GetBlocksFromNumberResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
